apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-demo
  namespace: scaling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-demo
  template:
    metadata:
      labels:
        app: cpu-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "3000m"
            memory: "256Mi"
          limits:
            cpu: "3000m"
            memory: "256Mi"