apiVersion: apps/v1
kind: Deployment

metadata:
  name: dynamodb-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dynamodb-app

  template:
    metadata:
      labels:
        app: dynamodb-app

    spec:
      serviceAccountName: dynamodb-sa

      containers:
      - name: app
        image: 588681235754.dkr.ecr.ap-south-1.amazonaws.com/irsa-dynamodb-app:latest

        imagePullPolicy: Always