apiVersion: apps/v1
kind: Deployment

metadata:
  name: calculator
  namespace: calculator

spec:
  replicas: 2

  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: calculator
          image: 588681235754.dkr.ecr.ap-south-1.amazonaws.com/calculator:f769e5ede005283141a2d11e4553c5a9efe1e92b
          imagePullPolicy: Always
          ports:
            - containerPort: 5000